2025-03-25 20:43:32,033 - ERROR - 程序執行失敗: Torch not compiled with CUDA enabled
2025-03-25 20:43:32,034 - ERROR - 堆疊追踪:
Traceback (most recent call last):
  File "D:\project\.HomeWorkProject\BCCT-Platform\model\main\main.py", line 68, in main
    engine = TrainingEngine(config, model, train_loader, val_loader)
  File "D:\project\.HomeWorkProject\BCCT-Platform\model\main\train.py", line 17, in __init__
    self.model = model.to(config.device)
  File "c:\Users\daniel\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1343, in to
    return self._apply(convert)
  File "c:\Users\daniel\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 903, in _apply
    module._apply(fn)
  File "c:\Users\daniel\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 903, in _apply
    module._apply(fn)
  File "c:\Users\daniel\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 903, in _apply
    module._apply(fn)
  File "c:\Users\daniel\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 930, in _apply
    param_applied = fn(param)
  File "c:\Users\daniel\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1329, in convert
    return t.to(
  File "c:\Users\daniel\anaconda3\lib\site-packages\torch\cuda\__init__.py", line 310, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
